apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dd-secrets
  namespace: dd-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dd-fake
  target:
    name: dd-secrets
    creationPolicy: Owner
  data:
    - secretKey: app-secret
      remoteRef:
        key: dd/staging/app-secret
